name: Run CloudLab Experiment

on:
  push:
    branches:
      - main

jobs:
  run-experiment:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Python Dependencies
        run: pip install xmltodict

      - name: Create PEM file from Base64 secret
        run: |
          printf '%s' "${{ secrets.CLOUDLAB_PEM_BASE64 }}" | base64 -d > cloudlab.pem
          chmod 600 cloudlab.pem

      - name: Run CloudLab Experiment Script
        env:
          USER: ${{ secrets.CLOUDLAB_USER }}
          PWORD: ${{ secrets.CLOUDLAB_PASS }}
          CERT: ./cloudlab.pem
          CLOUDLAB_PROJECT_NAME: ${{ secrets.CLOUDLAB_PROJECT_NAME }}
          CLOUDLAB_PROFILE_NAME: ${{ secrets.CLOUDLAB_PROFILE_NAME }}
        run: python example.py
