name: Run CloudLab Experiment

on:
  push:
    branches:
      - main

jobs:
  run-experiment:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Python Dependencies
        run: pip install xmltodict

      - name: Generate SSH Keypair for this run
        run: |
          ssh-keygen -t rsa -b 4096 -f id_rsa -N ""
          cat id_rsa.pub > public_key.txt
          echo "PRIVATE_KEY<<EOF" >> $GITHUB_ENV
          cat id_rsa >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV

      - name: Create PEM file from Base64 secret
        run: |
          echo "${{ secrets.CLOUDLAB_PEM_BASE64 }}" | base64 -d > cloudlab.pem
          chmod 600 cloudlab.pem

      - name: Run CloudLab Experiment Script
        env:
          USER: ${{ secrets.CLOUDLAB_USER }}
          PWORD: ${{ secrets.CLOUDLAB_PASS }}
          CERT: ./cloudlab.pem
          CLOUDLAB_PROJECT_NAME: ${{ secrets.CLOUDLAB_PROJECT_NAME }}
          CLOUDLAB_PROFILE_NAME: ${{ secrets.CLOUDLAB_PROFILE_NAME }}
        run: python example.py

      - name: SSH into CloudLab node
        run: |
          mkdir -p ~/.ssh
          echo "$PRIVATE_KEY" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          NODE_IP=$(cat node_ip.txt)
          ssh -o StrictHostKeyChecking=no tg996676@$NODE_IP 'echo "Connected via SSH!"'
